from snakemake.utils import validate

# setup
if "experiment" not in config:
    raise ValueError(
        "No experiment specified! Please provide an experiment name via '--config experiment=<name>' "
        "or run via './run.sh <experiment>'."
    )

configfile: "config/base.yaml"
configfile: f"config/experiments/{config['experiment']}.yaml"

validate(config, "../config/config.schema.yaml")

RESULTS_DIR = f"results/{config['experiment']}"


include: "rules/common.smk"


wildcard_constraints:
    tad_parameter=r"\d+",  # contains window size which must be an integer


localrules:
    all,
    gather_input_information,
    aggregate_tads,
    provide_input_files,
    include_tad_relations,
    compute_enrichments,
    create_figures,
    create_report,


actual_window_size_list = list(
    set(config["window_size_list"]) - {0, 1}
)  # remove majority vote for rules which need actual TADs


ruleorder: snp_majority_vote > aggregate_tads
ruleorder: snp_majority_vote > include_tad_relations
ruleorder: snp_majority_vote_narrow > aggregate_tads
ruleorder: snp_majority_vote_narrow > include_tad_relations


hic_sources_raw = config["samples"].keys()
hic_sources = generate_data_source_list(
    config["samples"], config.get("mcool_resolutions", {})
)


# rule definitions
rule all:
    input:
        RESULTS_DIR + "/results/final_enr.csv.gz",
        RESULTS_DIR + "/results/database_statistics/",
        RESULTS_DIR + "/post_analysis/",
        RESULTS_DIR + "/publication_figures/main/",
        RESULTS_DIR + "/publication_figures/tad_plots_multidataset/",
        RESULTS_DIR + "/publication_figures/tad_plots_multiwindowsize/",


# Optional targets:
# expand(
#     'results/hic_files/plots/{source}/heatmap.chr{chromosome}.pdf',
#     source=hic_sources,
#     chromosome=config['chromosome_list'],
# ),
# 'results/tads/plots/',
# expand(
#     'results/plots/{source}/{tad_parameter}/{filter}/',
#     source=hic_sources,
#     tad_parameter=config['window_size_list'],
#     filter=config['snp_filters'].keys(),
# ),
# expand(
#     'results/reports/report.{source}.{tad_parameter}.{filter}.pdf',
#     source=hic_sources,
#     tad_parameter=config['window_size_list'],
#     filter=config['snp_filters'].keys())


rule extract_cool_from_mcool:
    input:
        mcool=lambda wc: sample_url_from_source_wildcard(wc.source),
    output:
        cool=RESULTS_DIR + "/hic_files/cool/{source}.cool",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=10_000,
        hdf5_lock=1,
    script:
        "scripts/extract_cool_from_mcool.py"


rule extract_count_matrices:
    input:
        fname=lambda wc: cool_input_for_source_wildcard(wc.source),
    output:
        fname_matrix=RESULTS_DIR + "/hic_files/counts/{source}/{chromosome}/matrix.csv",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=10_000,
        hdf5_lock=1,
    script:
        "scripts/extract_count_matrices.py"


rule gather_input_information:
    input:
        fname_list=[url_wrapper(config["samples"][hic]) for hic in hic_sources_raw],
    output:
        fname=RESULTS_DIR + "/hic_files/info.csv",
    conda:
        "envs/python_stack.yaml"
    resources:
        hdf5_lock=1,
    params:
        samplename_list=list(hic_sources_raw),
    script:
        "scripts/gather_input_information.py"


rule install_extra_dependencies:
    output:
        touch(RESULTS_DIR + "/dependencies/extra_dependencies_installed.marker"),
    conda:
        "envs/python_stack.yaml"
    script:
        "scripts/install_extra_dependencies.py"


rule visualize_count_matrix:
    input:
        fname_matrix=RESULTS_DIR + "/hic_files/counts/{source}/{chromosome}/matrix.csv",
    output:
        fname_heatmap=RESULTS_DIR + "/hic_files/plots/{source}/heatmap.chr{chromosome}.pdf",
    log:
        notebook=(
            RESULTS_DIR + "/notebooks/VisualizeContactMatrix.{source}.{chromosome}.ipynb"
        ),
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=lambda wildcards, attempt: attempt * 20_000,
    notebook:
        "notebooks/VisualizeContactMatrix.ipynb"


rule compute_tads:
    input:
        fname=RESULTS_DIR + "/hic_files/counts/{source}/{chromosome}/matrix.csv",
        fname_info=RESULTS_DIR + "/hic_files/info.csv",
        fname_dep_marker=RESULTS_DIR + "/dependencies/extra_dependencies_installed.marker",
    output:
        fname=RESULTS_DIR + "/tads/data/{source}/{tad_parameter}/tads.chr{chromosome}.csv",
        topdom_input=temp(
            RESULTS_DIR + "/tads/data/{source}/{tad_parameter}/topdom/topdom_input.chr{chromosome}.tsv"
        ),
        topdom_output=RESULTS_DIR + "/tads/data/{source}/{tad_parameter}/topdom/topdom.chr{chromosome}.bed",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=30_000,
    params:
        prefix=(
            RESULTS_DIR + "/tads/data/{source}/{tad_parameter}/topdom/topdom.chr{chromosome}"
        ),
    script:
        "scripts/compute_tads.py"


rule aggregate_tads:
    input:
        fname_list=expand(
            RESULTS_DIR + "/tads/data/{source}/{tad_parameter}/tads.chr{chromosome}.csv",
            chromosome=config["chromosome_list"],
            allow_missing=True,
        ),
    output:
        fname=RESULTS_DIR + "/tads/data/tads.{source}.{tad_parameter}.csv",
    conda:
        "envs/python_stack.yaml"
    script:
        "scripts/aggregate_tads.py"


rule compare_tad_lists:
    input:
        tad_fname_list=expand(
            RESULTS_DIR + "/tads/data/tads.{source}.{tad_parameter}.csv",
            source=hic_sources,
            tad_parameter=actual_window_size_list,
        ),
    output:
        outdir=directory(RESULTS_DIR + "/tads/plots/"),
    log:
        notebook=RESULTS_DIR + "/notebooks/TADListComparison.ipynb",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=4_000,
    notebook:
        "notebooks/TADListComparison.ipynb"


rule provide_input_files:
    input:
        disgenet_fname=url_wrapper(config["input_files"]["disgenet"]),
        gwascatalog_fname=url_wrapper(config["input_files"]["gwascatalog"]),
        efo_fname=url_wrapper(config["input_files"]["exp_factor_ontology"]),
        so_fname=url_wrapper(config["input_files"]["sequence_ontology"]),
        dbsnp_hg19_fname=url_wrapper(config["input_files"]["dbsnp_hg19"]),
    output:
        disgenet_fname=RESULTS_DIR + "/input/disgenet.tsv",
        gwascatalog_fname=RESULTS_DIR + "/input/gwas_catalog.tsv",
        efo_fname=RESULTS_DIR + "/input/efo.owl",
        so_fname=RESULTS_DIR + "/input/so.owl",
        dbsnp_hg19_fname=RESULTS_DIR + "/input/dbSnp155Common_hg19.bb",
    conda:
        "envs/python_stack.yaml"
    script:
        "scripts/provide_files.py"


rule assemble_input_databases:
    input:
        disgenet_fname=RESULTS_DIR + "/input/disgenet.tsv",
        gwascatalog_fname=RESULTS_DIR + "/input/gwas_catalog.tsv",
        efo_fname=RESULTS_DIR + "/input/efo.owl",
        so_fname=RESULTS_DIR + "/input/so.owl",
        dbsnp_hg19_fname=RESULTS_DIR + "/input/dbSnp155Common_hg19.bb",
    output:
        db_fname=RESULTS_DIR + "/databases/initial.csv",
        raw_veps=RESULTS_DIR + "/databases/vep.csv",
    log:
        notebook=RESULTS_DIR + "/notebooks/AssembleInputDatabases.ipynb",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=3_000,
    notebook:
        "notebooks/AssembleInputDatabases.ipynb"


rule include_tad_relations:
    input:
        tads_fname=RESULTS_DIR + "/tads/data/tads.{source}.{tad_parameter}.csv",
        db_fname=RESULTS_DIR + "/databases/initial.csv",
        info_fname=RESULTS_DIR + "/hic_files/info.csv",
    output:
        db_fname=RESULTS_DIR + "/databases/per_source/snpdb.{source}.{tad_parameter}.csv",
        tad_length_plot=RESULTS_DIR + "/tads/length_plots/tad_length_histogram.{source}.{tad_parameter}.pdf",
    log:
        notebook=(
            RESULTS_DIR + "/notebooks/IncludeTADRelations.{source}.{tad_parameter}.ipynb"
        ),
    conda:
        "envs/python_stack.yaml"
    resources:
        notebook_slots=1,
    notebook:
        "notebooks/IncludeTADRelations.ipynb"


rule snp_majority_vote:
    input:
        fname_list=expand(
            RESULTS_DIR + "/databases/per_source/snpdb.{source}.{tad_parameter}.csv",
            tad_parameter=actual_window_size_list,
            allow_missing=True,
        ),
    output:
        fname=RESULTS_DIR + "/databases/per_source/snpdb.{source}.0.csv",
        fname_tads=RESULTS_DIR + "/tads/data/tads.{source}.0.csv",  # empty dummy
    log:
        notebook=RESULTS_DIR + "/notebooks/SNPMajorityVote.{source}.0.ipynb",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=3_000,
    params:
        tad_parameter_range=None,
        border_fraction_threshold=config["parameters"][
            "snp_majority_vote_border_fraction_threshold"
        ],
    notebook:
        "notebooks/SNPMajorityVote.ipynb"


rule snp_majority_vote_narrow:
    input:
        fname_list=expand(
            RESULTS_DIR + "/databases/per_source/snpdb.{source}.{tad_parameter}.csv",
            tad_parameter=actual_window_size_list,
            allow_missing=True,
        ),
    output:
        fname=RESULTS_DIR + "/databases/per_source/snpdb.{source}.1.csv",
        fname_tads=RESULTS_DIR + "/tads/data/tads.{source}.1.csv",  # empty dummy
    log:
        notebook=RESULTS_DIR + "/notebooks/SNPMajorityVote.{source}.1.ipynb",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=3_000,
    params:
        tad_parameter_range=[9, 10, 11, 12, 13],
        border_fraction_threshold=0.5,
    notebook:
        "notebooks/SNPMajorityVote.ipynb"


rule compute_enrichments:
    input:
        db_fname=RESULTS_DIR + "/databases/per_source/snpdb.{source}.{tad_parameter}.csv",
        tads_fname=RESULTS_DIR + "/tads/data/tads.{source}.{tad_parameter}.csv",
        info_fname=RESULTS_DIR + "/hic_files/info.csv",
    output:
        fname=RESULTS_DIR + "/enrichments/results.{source}.{tad_parameter}.{filter}.csv",
    log:
        notebook=RESULTS_DIR + "/notebooks/ComputeTADEnrichments.{source}.{tad_parameter}.{filter}.ipynb",
    conda:
        "envs/python_stack.yaml"
    resources:
        notebook_slots=1,
    notebook:
        "notebooks/ComputeTADEnrichments.ipynb"


rule create_figures:
    input:
        db_fname=RESULTS_DIR + "/databases/per_source/snpdb.{source}.{tad_parameter}.csv",
        enr_fname=RESULTS_DIR + "/enrichments/results.{source}.{tad_parameter}.{filter}.csv",
    output:
        outdir=directory(RESULTS_DIR + "/plots/{source}/{tad_parameter}/{filter}/"),
    log:
        notebook=(
            RESULTS_DIR + "/notebooks/CreateFigures.{source}.{tad_parameter}.{filter}.ipynb"
        ),
    conda:
        "envs/python_stack.yaml"
    resources:
        notebook_slots=1,
    notebook:
        "notebooks/CreateFigures.ipynb"


rule create_report:
    input:
        fname_enr=RESULTS_DIR + "/enrichments/results.{source}.{tad_parameter}.{filter}.csv",
    output:
        RESULTS_DIR + "/reports/report.{source}.{tad_parameter}.{filter}.pdf",
    conda:
        "envs/r_stack.yaml"
    script:
        "report/report.Rmd"


rule aggregate_results:
    input:
        database_files=expand(
            RESULTS_DIR + "/databases/per_source/snpdb.{source}.{tad_parameter}.csv",
            source=hic_sources,
            tad_parameter=config["window_size_list"],
        ),
        enrichment_files=expand(
            RESULTS_DIR + "/enrichments/results.{source}.{tad_parameter}.{filter}.csv",
            source=hic_sources,
            tad_parameter=config["window_size_list"],
            filter=config["snp_filters"].keys(),
        ),
    output:
        fname_data=RESULTS_DIR + "/results/final_data.csv.gz",
        fname_enr=RESULTS_DIR + "/results/final_enr.csv.gz",
    log:
        notebook=RESULTS_DIR + "/notebooks/AggregateResults.ipynb",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=lambda wildcards, attempt: (attempt + 2) * 10_000,
    notebook:
        "notebooks/AggregateResults.ipynb"


rule compute_database_statistics:
    input:
        fname=RESULTS_DIR + "/results/final_data.csv.gz",
        tad_fname_list=expand(
            RESULTS_DIR + "/tads/data/tads.{source}.{tad_parameter}.csv",
            source=hic_sources,
            tad_parameter=actual_window_size_list,
        ),
    output:
        outdir=directory(RESULTS_DIR + "/results/database_statistics/"),
    log:
        notebook=RESULTS_DIR + "/notebooks/DatabaseStatistics.ipynb",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=lambda wildcards, attempt: (attempt + 2) * 10_000,
    notebook:
        "notebooks/DatabaseStatistics.ipynb"


rule multi_run_post_analysis:
    input:
        fname_data=RESULTS_DIR + "/results/final_data.csv.gz",
        fname_enr=RESULTS_DIR + "/results/final_enr.csv.gz",
    output:
        outdir=directory(RESULTS_DIR + "/post_analysis/"),
    log:
        notebook=RESULTS_DIR + "/notebooks/MultiRunPostAnalysis.ipynb",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=lambda wildcards, attempt: (attempt + 2) * 10_000,
    notebook:
        "notebooks/MultiRunPostAnalysis.ipynb"


rule publication_figures:
    input:
        fname_data=RESULTS_DIR + "/results/final_data.csv.gz",
        fname_enr=RESULTS_DIR + "/results/final_enr.csv.gz",
        sketch_hicfile=cool_input_for_source_wildcard(config["sketch"]["data_source"]),
        sketch_tadfile=(RESULTS_DIR + "/tads/data/tads.{source}.{tad_parameter}.csv").format(
            source=config["sketch"]["data_source"],
            tad_parameter=config["sketch"]["window_size"],
        ),
    output:
        outdir=directory(RESULTS_DIR + "/publication_figures/main/"),
    log:
        notebook=RESULTS_DIR + "/notebooks/PublicationFigures.ipynb",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=lambda wildcards, attempt: (attempt + 5) * 10_000,
        hdf5_lock=1,
    notebook:
        "notebooks/PublicationFigures.ipynb"


rule supplementary_tadplots_multidataset:
    input:
        fname_data=RESULTS_DIR + "/results/final_data.csv.gz",
        sketch_hicfile=cool_input_for_source_wildcard(config["sketch"]["data_source"]),
        sketch_tadfile=(RESULTS_DIR + "/tads/data/tads.{source}.{tad_parameter}.csv").format(
            source=config["sketch"]["data_source"],
            tad_parameter=config["sketch"]["window_size"],
        ),
        tad_fname_list=expand(
            RESULTS_DIR + "/tads/data/tads.{source}.{tad_parameter}.csv",
            source=hic_sources,
            tad_parameter=10,
        ),
    output:
        outdir=directory(RESULTS_DIR + "/publication_figures/tad_plots_multidataset/"),
    log:
        notebook=RESULTS_DIR + "/notebooks/Supplementaries_TADPlots.ipynb",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=lambda wildcards, attempt: (attempt + 2) * 10_000,
    params:
        multitad_plot_type="multidataset",
    notebook:
        "notebooks/Supplementaries_TADPlots.ipynb"


rule supplementary_tadplots_multiwindowsize:
    input:
        fname_data=RESULTS_DIR + "/results/final_data.csv.gz",
        sketch_hicfile=cool_input_for_source_wildcard(config["sketch"]["data_source"]),
        sketch_tadfile=(RESULTS_DIR + "/tads/data/tads.{source}.{tad_parameter}.csv").format(
            source=config["sketch"]["data_source"],
            tad_parameter=config["sketch"]["window_size"],
        ),
        tad_fname_list=expand(
            RESULTS_DIR + "/tads/data/tads.{source}.{tad_parameter}.csv",
            source=config["parameters"]["main_dataset"],
            tad_parameter=actual_window_size_list,
        ),
    output:
        outdir=directory(RESULTS_DIR + "/publication_figures/tad_plots_multiwindowsize/"),
    log:
        notebook=RESULTS_DIR + "/notebooks/Supplementaries_TADPlots.ipynb",
    conda:
        "envs/python_stack.yaml"
    resources:
        mem_mb=lambda wildcards, attempt: (attempt + 2) * 10_000,
    params:
        multitad_plot_type="multiwindowsize",
    notebook:
        "notebooks/Supplementaries_TADPlots.ipynb"
