from snakemake.utils import validate

# setup
if "experiment" not in config:
    raise ValueError(
        "No experiment specified! Please provide an experiment name via '--config experiment=<name>' "
        "or run via './run.sh <experiment>'."
    )


configfile: "config/base.yaml"
configfile: f"config/experiments/{config['experiment']}.yaml"


validate(config, "../config/config.schema.yaml")

RESULTS_DIR = f"results/{config['experiment']}"


report: "report/workflow.rst"


include: "rules/common.smk"


wildcard_constraints:
    tad_parameter=r"\d+",  # contains window size which must be an integer


localrules:
    all,
    gather_input_information,
    aggregate_tads,
    provide_input_files,
    include_tad_relations,
    compute_enrichments,
    create_figures,
    create_report,


actual_window_size_list = list(
    set(config["window_size_list"]) - {0, 1}
)  # remove majority vote for rules which need actual TADs


ruleorder: snp_majority_vote > aggregate_tads
ruleorder: snp_majority_vote > include_tad_relations
ruleorder: snp_majority_vote_narrow > aggregate_tads
ruleorder: snp_majority_vote_narrow > include_tad_relations


hic_sources_raw = config["samples"].keys()
hic_sources = generate_data_source_list(
    config["samples"], config.get("mcool_resolutions", {})
)


# master target rule
rule all:
    """Target rule specifying final publication figures, enrichments, and statistics."""
    input:
        RESULTS_DIR + "/results/final_enr.csv.gz",
        RESULTS_DIR + "/results/database_statistics/",
        RESULTS_DIR + "/post_analysis/",
        RESULTS_DIR + "/publication_figures/main/",
        RESULTS_DIR + "/publication_figures/tad_plots_multidataset/",
        RESULTS_DIR + "/publication_figures/tad_plots_multiwindowsize/",


# modular rule includes
include: "rules/hic.smk"
include: "rules/tads.smk"
include: "rules/databases.smk"
include: "rules/enrichment.smk"
include: "rules/figures.smk"
