workdir: './pipeline_run/'
hicdata_dir: './hic_data/'


chromosome_list: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']
window_size_list: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

snp_filters:
    nofilter: null
    exonic: 'variant_group_{genome_assembly} == "exonic"'
    intronic: 'variant_group_{genome_assembly} == "intronic"'
    intergenic: 'variant_group_{genome_assembly} == "intergenic"'
    nonexonic: 'variant_group_{genome_assembly} != "exonic"'

input_files:
    disgenet: 'https://www.disgenet.org/static/disgenet_ap1/files/downloads/curated_variant_disease_associations.tsv.gz'
    gwascatalog: 'ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/gwas-catalog-associations_ontology-annotated.tsv'
    exp_factor_ontology: 'http://www.ebi.ac.uk/efo/efo.owl'
    sequence_ontology: 'https://github.com/The-Sequence-Ontology/SO-Ontologies/raw/master/so.owl'

annotation_sources:
    hg19: 'grch37.ensembl.org'
    hg38: 'www.ensembl.org'

parameters:
    associated_gene_source: mapped  # 'reported', 'mapped'
    allow_snp_multiplicity_in_enrichment: false
    enrichment_distribution: binom  # 'binom', 'hypergeom'
    enrichment_null_model: base_sample  # 'base_sample', 'snp_sample'
