workdir: './pipeline_run/'

samples:
    Dixon2012-H1hESC-HindIII-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Dixon2012-H1hESC-HindIII-allreps-filtered.10kb.cool
    Dixon2012-IMR90-HindIII-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Dixon2012-IMR90-HindIII-allreps-filtered.10kb.cool
    Dixon2015-H1_ME-HindIII-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Dixon2015-H1_ME-HindIII-allreps-filtered.10kb.cool
    Dixon2015-H1_MS-HindIII-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Dixon2015-H1_MS-HindIII-allreps-filtered.10kb.cool
    Dixon2015-H1_NP-HindIII-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Dixon2015-H1_NP-HindIII-allreps-filtered.10kb.cool
    Dixon2015-H1_TB-HindIII-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Dixon2015-H1_TB-HindIII-allreps-filtered.10kb.cool
    Dixon2015-H1_hESC-HindIII-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Dixon2015-H1_hESC-HindIII-allreps-filtered.10kb.cool
    Jin2013-IMR90-HindIII-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Jin2013-IMR90-HindIII-allreps-filtered.10kb.cool
    Rao2014-GM12878-DpnII-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Rao2014-GM12878-DpnII-allreps-filtered.10kb.cool
    Rao2014-GM12878-MboI-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Rao2014-GM12878-MboI-allreps-filtered.10kb.cool
    Rao2014-HMEC-MboI-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Rao2014-HMEC-MboI-allreps-filtered.10kb.cool
    Rao2014-HUVEC-MboI-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Rao2014-HUVEC-MboI-allreps-filtered.10kb.cool
    Rao2014-IMR90-MboI-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Rao2014-IMR90-MboI-allreps-filtered.10kb.cool
    Rao2014-NHEK-MboI-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Rao2014-NHEK-MboI-allreps-filtered.10kb.cool
    Selvaraj2013-GM12878-HindIII-allreps-filtered-10kb: ftp://cooler.csail.mit.edu/coolers/hg19/Selvaraj2013-GM12878-HindIII-allreps-filtered.10kb.cool

chromosome_list: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']
window_size_list: [0,1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

tad_borders:  # format: [in-distance, out-distance] relative to (both) TAD ends
    10in: [10000, 0]
    20in: [20000, 0]
    50in: [50000, 0]
    100in: [100000, 0]
    150in: [150000, 0]
    200in: [200000, 0]
    300in: [300000, 0]

snp_filters:
    nofilter: null
    exonic: 'variant_group_{genome_assembly} == "exonic"'
    intronic: 'variant_group_{genome_assembly} == "intronic"'
    intergenic: 'variant_group_{genome_assembly} == "intergenic"'
    nonexonic: 'variant_group_{genome_assembly} != "exonic"'

input_files:
    disgenet: 'https://www.disgenet.org/static/disgenet_ap1/files/downloads/curated_variant_disease_associations.tsv.gz'
    gwascatalog: 'ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/gwas-catalog-associations_ontology-annotated.tsv'
    disease_ontology: 'https://github.com/DiseaseOntology/HumanDiseaseOntology/raw/master/src/ontology/doid.owl'
    exp_factor_ontology: 'http://www.ebi.ac.uk/efo/efo.owl'
    sequence_ontology: 'https://github.com/The-Sequence-Ontology/SO-Ontologies/raw/master/Ontology_Files/so.owl'

annotation_sources:
    hg19: 'grch37.ensembl.org'
    hg38: 'www.ensembl.org'

parameters:
    associated_gene_source: mapped  # 'reported', 'mapped'
    allow_snp_multiplicity_in_enrichment: false
    enrichment_distribution: hypergeom  # 'binom', 'hypergeom'
    enrichment_null_model: snp_sample  # 'base_sample', 'snp_sample'
    main_dataset: Rao2014-IMR90-MboI-allreps-filtered-10kb
    snp_majority_vote_border_fraction_threshold: 0.3

sketch:
    region: ['chr11', 123050000, 123550000]
    data_source: Rao2014-IMR90-MboI-allreps-filtered-10kb
    window_size: 10
